create or replace TRIGGER  PMO_DEVELOPER.TRG_LAST_UPDATED_LANGUAGE
BEFORE INSERT or UPDATE
    on LANGUAGE
    FOR EACH ROW
    BEGIN
        :NEW.LAST_UPDATED_TIMESTAMP := CURRENT_TIMESTAMP;
    END;

